### ISSUE TITLE
Tombol Upload Dokumen Missing

### ISSUE THREAD

**Issue by RenoXF** [GMDP-Developers/Billing-ISP#1]
![Image](https://github.com/GMDP-Developers/Billing-ISP/assets/52855068/1d7edc5b-5dd9-410d-b9b6-0838a8abbc87)

**Comment by vermaysha** [comment]
Hilang dimenu apa mas ? @RenoXF

**Comment by RenoXF** [comment]
admin dong kang, kan yang bisa nambah dokumen admin
